FROM node:18.20.3-alpine3.18 as builder

WORKDIR /app

COPY ../package*.json ./
RUN npm install
COPY ../ .
RUN npx nx build frontend --prod

FROM node:18.20.3-alpine3.18 as runner

WORKDIR /app

COPY --from=builder /app/dist/apps/frontend ./
EXPOSE 4000
CMD ["node", "server/server.mjs"]
